version: '3.1'

services:

  # Use root/example as user/password credentials
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306

  client1:
    image: python:3.8
    command:
      - "./wait-for-it.sh"
      - "db:3306"
      - "--"
      - "./start.sh"
    environment:
      DB_HOST: haproxy24
    working_dir: /usr/src/myapp
    volumes:
      - ./:/usr/src/myapp
    depends_on:
      - db

  haproxy24:
    build: .
    command: haproxy -W -db -f /usr/local/etc/haproxy/haproxy.cfg -p /var/run/haproxy/haproxy.pid -x /var/run/haproxy/haproxy.sock
    volumes:
      - ./usr-local-etc-haproxy:/usr/local/etc/haproxy
    ports:
      - 9001:8080
      - 19001:9000
      - 5555:5555